use practice

SELECT * FROM VIHARA
SELECT * FROM TECH

UPDATE TECH SET ID = 5 WHERE NAME = 'VINAY'

SELECT * FROM VIHARA
UNION
SELECT * FROM TECH

SELECT * FROM VIHARA INNER JOIN TECH ON VIHARA.ID = TECH.ID

SELECT * FROM VIHARA LEFT OUTER JOIN TECH ON VIHARA.ID = TECH.ID

SELECT * FROM VIHARA RIGHT OUTER JOIN TECH ON VIHARA.ID = TECH.ID

SELECT * FROM VIHARA FULL OUTER JOIN TECH ON VIHARA.ID = TECH.ID

SELECT * FROM VIHARA CROSS JOIN TECH

SELECT * FROM VIHARA,TECH WHERE VIHARA.ID = TECH.ID

SELECT * FROM VIHARA,TECH WHERE VIHARA.ID > TECH.ID

SELECT * FROM VIHARA,TECH WHERE VIHARA.ID < TECH.ID

SELECT * FROM VIHARA,TECH WHERE VIHARA.ID >= TECH.ID

SELECT * FROM VIHARA,TECH WHERE VIHARA.ID <= TECH.ID